version: '3.8'

services:
  easia-green-api:
    container_name: easia-green-api
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
      - ./logs:/usr/src/app/logs
      - ./store:/usr/src/app/store
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]

# ➕ Nếu cần GPU với NVIDIA Container Toolkit:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [gpu]
