#version: "3.9"

services:
  py-gpu:
    build: .
    container_name: py-gpu-container
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./app:/app       # Mount thư mục local để chạy code
    working_dir: /app
    command: ["python", "main.py"]
