#(Python + CUDA)
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

# Cài Python & các tiện ích cơ bản
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-dev python-is-python3 \
    git curl nano && \
    rm -rf /var/lib/apt/lists/*

# Cài các thư viện Python cần thiết (tùy bạn mở rộng sau)
RUN pip install --upgrade pip && \
    pip install torch torchvision tensorflow

WORKDIR /app

CMD [ "python", "main.py" ]
