# version: "3.9"

services:
  fastapi-red:
    build:
      context: ./easia-red
    ports:
      - "8000:8000"

  fastapi-blue:
    build:
      context: ./easia-blue
    ports:
      - "8001:8001"

  netcore:
    build:
      context: ./easia
    ports:
      - "5000:80"
